language: python
python:
  - "3.9"
  - "3.8"
  - "3.7"
install:
  - sudo apt-get update
  - sudo apt-get install -y openssl libssl-dev  # Update OpenSSL
  - openssl version  # Verify OpenSSL version
  - pip install "urllib3<2.0"  # Correct version of urllib3
  - pip install -r requirements.txt
script:
  - pytest