language: python
python:
  - "3.9"
  - "3.8"
  - "3.7"
  # - "3.6"
  # - "3.5"
  # - "3.4"
  # - "2.7"
install:
  - pip install -r requirements.txt
before_script:
  - echo $SLACK_API_KEY
  - echo $SQLALCHEMY_DATABASE_URI
script:
  - pytest
# after_success:
# - render deploy --service <SERVICE_NAME> --branch <BRANCH_NAME> --token $RENDER_API_KEY
