language: python
python:
  - "3.9"
  - "3.8"
  - "3.7"

install:
  - pip install -r requirements.txt

services:
  - postgresql

addons:
  postgresql: "13"

env:
  global:
    - SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://postgres@localhost:5432/task_list_api_test

before_script:
  - echo "Starting PostgreSQL..."
  - psql -c '\l' -U postgres  # Проверить список баз
  - psql -c 'create database task_list_api_test;' -U postgres || exit 1

script:
  - pytest

# after_success:
#   - render deploy --service <SERVICE_NAME> --branch <BRANCH_NAME> --token $RENDER_API_KEY