# Exported from Render on 2024-12-18T05:36:46Z
databases:
- name: task_list-db
  databaseName: task_list_db_2l3f
  user: task_list_db_2l3f_user
  plan: free
  region: oregon
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "16"
version: "1"
